networks:
  internal-app:
    external: true
  internal-db:
    external: true

services:
  backend:
    image: ghcr.io/khairuonwork/gofiber-backend:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - DOCKER_SWARM=true
      - DB_USER=XXXX
      - DB_PASSWORD=XXXX
      - DB_HOST=XXXX
      - DB_PORT=XXXX
      - DB_NAME=XXXX
      - DB_SSLMODE=disable
      - REDIS_HOST=XXXX
      - REDIS_PORT=XXXX
      - APP_ENV=production
      - JWT_ACCESS_TOKEN_SECRET=secret
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - SMTP_MAIL=XXXX
      - SMTP_PASSWORD=XXXX
      - APP_PORT=8080
    networks:
      - internal-app
      - internal-db
    ports:
      - "8080:8080"
